### ISSUE TITLE
Duplicate tags issue

### ISSUE THREAD

**Issue by harrisondesbrosses** [standardnotes/forum#1122]
Hello!

It has been quite awhile since I've posted here.

I've been having an issue with duplicate tags in one particular area of my collections of notes for over a year, but have been too lazy to do anything about it until now. I've got a few parent notes "Personal, Research, and Studio". My problem is within my studio notes category, where a two tags "Art" and "Notes" are duplicated.  

I've gone through these tags and have seen that they each contain their own notes, the same notes are not duplicated across the duplicated tags. 

I've attempted using the batch manager to clear these duplicate tags, but they do not show up under a search (but duplicate notes do). I've attached a screengrab showing the lack of results from the batch manager.

I've searched through both open and closed issues and found one note from @mobitar that I think might have been my issue "Strange. Might be a references issue. That is, essentially, if one tag has 5 notes and the duplicate has 4, they might not be marked duplicates." – however this wasn't the case with me. 

I would be willing to manually do this work, but it's super tricky given there is no way to differentiate between the two tags when trying to remove the "problematic" one. Also, it's hard to label which one is problematic given what I said about each tag being linked to unique notes despite having the same tag name.

I'm stumped, and my obsessive compulsiveness with regards to clarity in archiving / file naming conventions is starting to make this a huge cosmetic issue for me haha.

Any help would be greatly appreciated!
![Screen Shot 2020-10-28 at 15 08 57](https://user-images.githubusercontent.com/22471894/97486847-69dbbe00-1932-11eb-84e9-3f67ebb7c1bc.png)

**Comment by JaspalSuri** [comment]
Hi @harrisondesbrosses,

Thank you for the detailed report! I'm afraid I wasn't able to reproduce the issue where the subtags weren't discovered by the batch manager despite having different types and amounts of notes using each. I tested both the latest stable version of the web app (v3.4.10) and the latest beta (v.3.5.1 b05) of the desktop app as well. I also wasn't able to create duplicate folders in the beta app (but could create duplicate subtags).  

Can you provide a screenshot of the tag hierarchy and obscure any personal info? With the Folders extension activated, you should be able to click on the circle on the left of the tags whose lists you'd like to collapse.

Can I ask what version of Standard Notes you're currently running? The number can be located by clicking on the `Account` button and then looking at the text that appears immediately above it. It should say something like `v.3.4.10`.

What operating system and/or web browser are you running Standard Notes in? 

Although unlikely, can you try reinstalling the Quick Tags and Folders extensions to see if it makes a difference?

**Comment by harrisondesbrosses** [comment]
@JaspalSuri 

Thanks for the reply!

I'm running 3.4.10 on all of my machines (desktop, laptop (both OSX, but with desktop running 10.13.16 on a Hackintosh, and the laptop running Mojave) and the latest iOS. I never run Standard Notes in a browser, I didn't even know that was possible.

Tag hierarchy screenshot is attached!

**Comment by harrisondesbrosses** [comment]
Additionally, I can confirm that the reinstalling of folders / auto complete / quick tags didn't help. However, uninstalling folder gave me the chance to see just how many notes I had in the problematic folders / tags, see attached.
![Screen Shot 2020-11-02 at 07 46 06](https://user-images.githubusercontent.com/22471894/97869512-9fd8c380-1cdf-11eb-9bb4-be7f2981810a.png)

**Comment by JaspalSuri** [comment]
Thanks for letting me know and thanks for the screenshots! Can you try updating to the latest version of the desktop app and let me know if it's been fixed? It's a major release with several under-the-hood improvements and contains several bug fixes (some which are fixed coincidentally). It'll be good to know whether it's resolved this issue, that way I can update my report accordingly. 🙂

**Comment by harrisondesbrosses** [comment]
@JaspalSuri I can confirm I still have the duplicate tag issue upon updating to 3.5.1

**Comment by JaspalSuri** [comment]
Thank you so much for letting us know! I will add it to my report and hopefully we'll find a way to reproduce it and come up with a fix.

**Comment by baptiste-grob** [comment]
Hi @harrisondesbrosses, while I'm afraid we don't have an automated solution for you, something you could do is creating a new note from the All Notes view and giving it the Studio.Art tag. This will let you see which tag the app is defaulting to, and you could then reassign the notes from the _other_ tag to that one.

**Comment by harrisondesbrosses** [comment]
@baptiste-grob 

I am in the process of doing this right now, but it is arduous! How can I avoid this kind of duplication in the future? I'm afraid if this happens again I will not be able to sacrifice this kind of time again. I'm working off my desktop machine, would it be wise to uninstall + reinstall Standard Notes before opening it on my laptop and mobile device? Would that prevent sync issues?

**Comment by JaspalSuri** [comment]
The update to v3.5 should have greatly reduced duplication and sync related issues. Instead of having to uninstall the app, you could sign out of one device, sign into another to confirm that your password and 2FA option still work, and then sign out of all the apps and sign back in again.

**Comment by harrisondesbrosses** [comment]
@JaspalSuri Ok! Done. No issues thus far.

**Comment by JaspalSuri** [comment]
That's great to hear; thank you for letting me know!
