### ISSUE TITLE
Auto-update never actually happens.

### ISSUE THREAD

**Issue by thirashima** [standardnotes/forum#3527]
### Discussed in https://github.com/standardnotes/forum/discussions/2589

<div type='discussions-op-text'>

<sup>Originally posted by **thirashima** August 16, 2022</sup>
Experiencing this with the mac app. Auto-update will show that an update is available, but the app will never actually download and install the update, no matter how long I leave the app open. The "Enable Automatic Updates" option is checked. I wish there was an option in the menu to make it go ahead and install the update now. 
<img width="267" alt="image" src="https://user-images.githubusercontent.com/12535/184919513-1d7f89ec-9526-4c35-be16-d05c34c3cafb.png"></div>

**Comment by Nephilimi** [comment]
I think this hit me on windows at the last update. Previous auto updates worked but last one just never did and I had to manually update it which went through no problem. I don't know how far out of date I was (one or two releases max) but I'm now on current 3.192.4.

**Comment by Nephilimi** [comment]
By my prior comment I meant I had to download the installer and update it with that. Telling the app to update inside the app didn't work. 

3.192.4 update to 3.192.13 appeared to work just fine when asked to update in the app after the app let me know there was an update available. 

I think this one is fixed.

**Comment by therealrodk** [comment]
I am on the Mac app, using version 3.201.10 of Standard Notes. I have only had this app for a few months, but Automatic Updates has never worked, so this bug is definitely not fixed. Or it has been reintroduced.

iMac
Retina 4K, 21.5-Inch, 2019
Processor 3 GH 6-Core Intel Core
Graphics Radeon Pro 560X 4 GB
Memory 64 GB 2667 MHz DDR4
macOS 15.7.4 (24G517)
