### ISSUE TITLE
1) Standard Notes on iPhone keeps logging out and 2) why not use facial recognition

### ISSUE THREAD

**Issue by LeisureTime69** [standardnotes/forum#3535]
I've been using Standard Notes for a couple of years without any issues. However, for the last two months or so it keeps logging me out on my iPhone 14 Pro Max (with all the latest updates). This is annoying because I have to copy and paste my email address and a very long random password from Apple Notes to log back in. Why can't standard notes just use facial recognition like other apps? Even my banks use facial recognition.

I've tried completely uninstalling and reinstalling the app but that did not fix it.

Is there any solution to this?

**Comment by chrismox** [comment]
Same experience here, been like this for a couple of months on my iPhone and iPad.

**Comment by Nephilimi** [comment]
I've also noticed this behavior, it logs me out every couple of weeks, maybe a month? I'm using 2FA and it takes a bit to get logged back in and I don't think I've experienced this with any other note taking app. Honestly, it's really disruptive when it happens as I need to make notes on the go.

**I was thinking this was intentional, but be this a bug or indented behavior this needs to stop.**

**Comment by effieeee** [comment]
Hi all, just wanted to double check if what you're experiencing is similar to the cases described in #3510? I'd like to confirm whether or not this is a resurgence of the issue. Please also note that you may need to sign out and sign back into your account on **all devices** that you were signed into.

P.S.
You can enable the **biometrics lock** on the mobile app, if you'd like to unlock the app with biometrics (e.g. Face ID) after you've already signed into the app with your password:
 
![mobile biometrics lock resize](https://github.com/standardnotes/forum/assets/54989748/556a2a3c-a5eb-433f-8c36-299f7bdde0a1)

**Comment by Nephilimi** [comment]
After reading #3510 I don't feel like this is the same problem. After entering the TOTP 2FA challenge I **DO** get logged in, where as in that case it seems like they never got logged in at all. 

In my case I get kicked out after a period of time passes, a week or two.

**Comment by effieeee** [comment]
Hi @Nephilimi, to further describe the issue that was being encountered in #3510, the users were actually already logged into the app, but they were encountering a request to **re-authenticate** their session on the app by re-entering their account email and password. Users who had 2FA active on their accounts would have also had to enter 2FA for verification during this process.

What would happen is that after re-entering their credentials, the re-authentication prompt still appears soon after, either just a few minutes after, to as long as a week or two later. After we deployed some fixes, some affected users still needed to sign out and sign back into their accounts on all devices, or even reinstall the app completely on their devices

When you mention that your issue is different in that you get "kicked out" of the app, do you mean that you are **completely logged out**, such that when you relaunch the app, it's as though it was newly installed again, without any account signed in? Like the others on this thread as well, have you only noticed this on iOS devices so far?

**Comment by Nephilimi** [comment]
@effieeee 
>  still needed to sign out and sign back into their accounts on all devices, or even reinstall the app completely on their devices

I logged into the web version and used that session to go into "sign out other sessions" and used the red End Sessions button to log out of all my other devices, then I logged out of that session. I've logged back in on ios and windows 10 app so far. 

I guess now we wait.

**Comment by LeisureTime69** [comment]
> Hi all, just wanted to double check if what you're experiencing is similar to the cases described in #3510? I'd like to confirm whether or not this is a resurgence of the issue. Please also note that you may need to sign out and sign back into your account on **all devices** that you were signed into.
> 
> P.S. You can enable the **biometrics lock** on the mobile app, if you'd like to unlock the app with biometrics (e.g. Face ID) after you've already signed into the app with your password:
> 

The issue is still happening for me. However, I just enabled biometric login (thank you!) so this will probably be an acceptable solution for me.

**Comment by Nephilimi** [comment]
@LeisureTime69 
> I just enabled biometric login

My understanding is it won't. The biometric login secures the app against people that don't use a phone lock and prevents others from opening the notes app. The app still needs to use password/2FA to access the note sync server, that's the part that's getting kicked out.

**Comment by LeisureTime69** [comment]
Yeah, looks like you are right. It has been working for the last few days; I don't have 2FA enabled so it just logged me right in. That's the way it should work. But today it gave me the "Please enter your account email and password" message and (oddly I thought) showed me the notes even though I didn't log in, but had a message "Sync Unreachable / Changes saved offline". Sigh. 

I'm not sure about this (I will try to pay more attention in the future), but is it possible that it happens when I leave my home wifi and then using cellular?

**Comment by Nephilimi** [comment]
OK, this might not be iphone related? I was forced to log into the windows app again today, about 9 days after my post above where I forced everything out and logged in fresh on all devices. Checking the phone and telling it to sync, it's still logged in and happy. 

Over the past week (but not today or yesterday) standard notes windows did some auto updates (3.193.2) and it was happy to sync after that update. 

Also yes it's odd that you can still see notes and everything in this state, I don't know if that's intentional or not.

**Comment by effieeee** [comment]
Hi @Nephilimi, thank you for the update, I've notified the team regarding a possible recurrence of the issue, along with the other new reports of it on the forum. We'll do our best to keep you posted, though you may also check #3513 as a related thread 🙏

**Comment by effieeee** [comment]
Hi all, the team was able to confirm an issue which affected the active user sessions, though a server wide fix was deployed earlier today. If you are still experiencing issues, please try signing out and signing back into your account, similar to what was done with the reauthentication issues in the past 🙏

**Comment by Nephilimi** [comment]
I was just forced out again on iOS.

**Comment by effieeee** [comment]
@Nephilimi, I'm sorry to hear this, may I know if you've also tried reinstalling the app on your device, apart from signing out and signing back into your account after the fix? If you use iCloud for backing up the app data, please also try removing Standard Notes from the iCloud backups to ensure that the app is cleanly reinstalled

1. Open the Settings app, and navigate to your iCloud backups with the following path: [Your name and iCloud account username (at the top)] → iCloud → Manage Storage → Backups → [Tap on the correct device]
2. Wait for the list of apps to load.
3. Finally, locate the Standard Notes app and tap on the toggle button to remove the current and all future backups of the app from iCloud.
4. From there, please reinstall the app and sign in again.

For others here that may still be experiencing reauthentication issues in spite of performing the steps mentioned above, please confirm here as well 🙏

**Comment by Nephilimi** [comment]
@effieeee I did all that and I'm signed back in again.

**Comment by chrismox** [comment]
> For others here that may still be experiencing reauthentication issues in spite of performing the steps mentioned above, please confirm here as well 🙏

This is still an issue for me. All devices except my iPhone seem to stay logged in, whereas my iPhone asks me to re-enter my login credentials fairly regularly (roughly every couple of days at the moment).

**Comment by LeisureTime69** [comment]
OP here. Mine has been working fine since effieeee said "the team was able to confirm an issue which affected the active user sessions, though a server wide fix was deployed earlier today."  All I did was make sure I was on the latest app version. Also, I am using Face ID but not 2FA. Nor am I using iCloud.

**Comment by LeisureTime69** [comment]
> OP here. Mine has been working fine since effieeee said "the team was able to confirm an issue which affected the active user sessions, though a server wide fix was deployed earlier today." All I did was make sure I was on the latest app version. Also, I am using Face ID but not 2FA. Nor am I using iCloud.

I spoke too soon. I was unable to log in with Face ID last night (May 2, 2024) when I was on 5G outside my home WiFi (not sure if that is related or not). 

"Your credentials are needed for <email> to refresh your session with the server"

**Comment by effieeee** [comment]
Hi @LeisureTime69, I'm sorry to hear that the issue seems to have happened again for you. I'm not sure if you were able to try it out as well, but were you able to try reinstalling the app on your device? Since you do not use iCloud to back up app data, just directly reinstalling the app will suffice.

If you're not sure about whether or not there are some unsaved changes on your device as well, you can choose to [export a backup](https://standardnotes.com/help/14/how-do-i-create-and-import-backups-of-my-standard-notes-data) of your notes first, before you proceed with reinstalling the app.

**Comment by Nephilimi** [comment]
iOS app kicked me out again today. I don't know if it's related or not but I did 17.5.1 this morning. I also hadn't used standard notes on the phone for a day or three.

**Comment by effieeee** [comment]
Hi @Nephilimi, I see, though yes the OS update may have something to do with it in your case. Can you try signing out and signing back into your account first, then monitor the issue again for the next few days?

**Comment by Nephilimi** [comment]
> Can you try signing out and signing back into your account first, then monitor the issue again for the next few days?

@effieeee The core problem is we get signed out without requesting sign out. So yes, I signed back in on my iphone already. We are asking for less of this.

**Comment by Nephilimi** [comment]
iOS app kicked me out again today. I know I used it last night and it worked fine, this morning I'm looking at the login screen again. 

edit; looking back on my post history this seems weekly for me.

**Comment by effieeee** [comment]
Hi @Nephilimi I see, I'm sorry to hear that the issue persists. If this is the case, we may also need to look into other account specific issues for this, so can you send us an email at help@standardnotes.com using your Standard Notes account email? @LeisureTime69 if the issue might still be happening on your end as well, please also contact us at help@standardnotes.com 🙏

**Comment by chrismox** [comment]
Hi,

To add weight to this issue, I am still experiencing the same login problems on my IOS devices. @effieeee I know we spoke by email and you went to great lengths to help me solve this, but the problem remains and, if the experience of others above is to be understood, the issues are clearly broader than being account-specific.

**Comment by chrismox** [comment]
Now my Windows 10 desktop app is asking me for my login credentials.

**Comment by effieeee** [comment]
Hi all, on behalf of the team I’d like to apologize that this issue persisted on your end in the past month. While these incidents were not as widespread as they were back in April, the developers were able to implement some changes on the server which should help further extend the validity of the user’s session tokens, and you should immediately see an improvement on your end after you sign out and sign back into your account. You may also try reinstalling the app on your devices if you’d like to ensure that you start over from a clean slate on the device.

Should you find no improvement in spite of the changes mentioned, please let us know here 🙏

**Comment by LeisureTime69** [comment]
> Hi all, on behalf of the team I’d like to apologize that this issue persisted on your end in the past month. While these incidents were not as widespread as they were back in April, the developers were able to implement some changes on the server which should help further extend the validity of the user’s session tokens, and you should immediately see an improvement on your end after you sign out and sign back into your account. You may also try reinstalling the app on your devices if you’d like to ensure that you start over from a clean slate on the device.

Thanks for your attention to this issue. I had to sign in again last week. It does seem less than it was a month or two ago.

**Comment by Nephilimi** [comment]
I have not had any of these apps re-ask for sign in sense my last post above. 
Thanks for continuing to work on this!

**Comment by joaofl** [comment]
Hi @effieeee 
Thanks for the attention. I confirm that re-authentication issue is not there when I use the stantardnotes online services, but the problem is **still there** for the self-hosted version.

Maybe the docker images are still outdated?

**Comment by coryduude** [comment]
Hi all -
Can confirm that I'm experiencing the same issue on a fresh install of the self-hosted server. App is completely unusable at this point. :(

**Comment by teon** [comment]
I can confirm that selhosted is broke and unusable- the "Please enter your account email and password." just "loops" doesn't matter how many times I enter the credentials there are two dialogs 1) the login dialog (again) and underneath it is *Your session has been successfully restored.* - but it's actually not as it's asking for the password again.

**Comment by teon** [comment]
@effieeee To help from what I see in the server logs after logging in still there is an error in logs:
**No cookies provided for cookie-based session token.**

**Comment by LeisureTime69** [comment]
FWIW, I am the OP and the issue seems to have been fixed for months now, at least for me. I hesitate to say that in order not to jinx it...

**Comment by Nephilimi** [comment]
> FWIW, I am the OP and the issue seems to have been fixed for months now, at least for me. I hesitate to say that in order not to jinx it...

I’ll confirm that on the paid server, but they are talking about it persisting on the self hosted version. 👨‍🔧

**Comment by teon** [comment]
@LeisureTime69 @Nephilimi exactly (self hosted did not have an update for months now)!
It's a real shame that even though I have bought the offline subscription it never worked. I had so many issues that in the end they have refunded me - clearly saying - if not directly - that they won't support self-hosted and only focus on cloud.

**Comment by Nephilimi** [comment]
Self hosted people with login issues, try this solution; https://github.com/standardnotes/forum/issues/3635#issuecomment-2340351845

**Comment by teon** [comment]
@Nephilimi WOW, that solved it! Thank you <3

**Comment by deflexes** [comment]
My Standard Notes on my Ipad, is well just completely broken it used to work just fine but then it stopped loading, so I deleted and tried to login but it's just stuck on the login page frozen.
