### ISSUE TITLE
Save error when loading web app

### ISSUE THREAD

**Issue by Larch35** [standardnotes/forum#672]
I use Standard Notes on Android but also use the web apps on my desktop and laptop - on both machines I have it open as a pinned tab in Firefox (latest version). This works fine on the desktop, but for some reason there's a problem on the laptop - every time I boot up and open Firefox, the web app gives me the following error:

"The note you are attempting to save can not be found or has been deleted. Changes you make will not be synced. Please copy this note's text and start a new note."

It then shows the titles for all my notes, but no contents. I have to refresh the tab in order to see the contents. This doesn't happen on the desktop. Any ideas?

**Comment by mobitar** [comment]
Hmm, never heard of this issue before. Although there have been various issues in the past related to pinned Firefox tabs. It sounds like it may be loading some cached state. Is there a way to force pinned tabs to refresh automatically on open?

**Comment by Larch35** [comment]
Hi, thanks for the suggestion. It looks like there's no native way in Firefox to do that, although it may be achievable via an extension. I'll have a play around with pinned, unpinned, opening the tab anew etc and see how it goes.

**Comment by Larch35** [comment]
Hi, thanks for the suggestion. It looks like there's no native way in Firefox to do that, although it may be achievable via an extension. I'll have a play around with pinned, unpinned, opening the tab anew etc and see how it goes.

**Comment by Larch35** [comment]
Back to its old behaviour now, and the error appears whether the tab is pinned or not. Will see what it does when opening the tab afresh rather than via auto session restore.

**Comment by Larch35** [comment]
... and that works fine. Just can't leave a SN tab open on there. Perplexed as to why this is an issue on my laptop but not my desktop (same OS, same browser).

**Comment by austil** [comment]
I got the exact same issue ! That'd been annoying me for months.
Using Firefox with Standard Notes always in a pinned tab.

Here is what's going on in the console :

```
TypeError: "this.note.tagsString is not a function"
Sync observer exception TypeError: "e.getAppDataItem is not a function"
Sync observer exception TypeError: "this.note.tagsString is not a function"
Sync observer exception TypeError: "h.note.content is undefined"
TypeError: e.createContentJSONFromProperties is not a function
Sync observer exception TypeError: "h.note.content is undefined"
Sync observer exception TypeError: "this.note.tagsString is not a function"
Sync observer exception TypeError: "this.note.tagsString is not a function"
Sync observer exception TypeError: "h.note.content is undefined"
TypeError: e.createContentJSONFromProperties is not a function
```

Then I refresh the app and everything is fine, no error in the console.

Hope this help.

**Comment by mobitar** [comment]
We can't replicate this consistently I'm afraid. What FF and OS version?

**Comment by austil** [comment]
Firefox 72.0.1 - Ubuntu 18.04.03 LTS

It's consistent on my machine :smile:, is it hard to get a dev build up and running ? If no can you point me to the code leading up to this popup so I can have a more detailed look at the stack ?

**Comment by johnny243** [comment]
I was able to replicate this issue:

![image](https://user-images.githubusercontent.com/5891646/72836318-b4713100-3c62-11ea-9e07-617add108146.png)

The error message seems to be coming from [this](https://github.com/standardnotes/web/blob/badadba8f8f215fb86242679c4076302a13f246d/app/assets/javascripts/app/controllers/editor.js#L306) line.

Using Firefox 72.0.1 (64-bit) on Ubuntu 19.10

**Comment by johnny243** [comment]
This issue is fixed with [#356](https://github.com/standardnotes/web/pull/356).

**Comment by austil** [comment]
I confirm this quirk is gone ! Thank you again !

**Comment by austil** [comment]
Hum, I've encountered another behavior, an infinite page reload :

![standard_note_infinite_reload](https://user-images.githubusercontent.com/3978482/74108973-a8043800-4b7f-11ea-9a8c-fa787f433e32.gif)

**Comment by austil** [comment]
Hey, the bug is back and I've noticed that my app went from 3.3.3 to 3.3.2. What's going on ? :smiley:

**Comment by mobitar** [comment]
We never went to 3.3.3.. We just released 3.3.2 however (from 3.3.1)

**Comment by austil** [comment]
Ok, my bad. I probably meant 3.3.0 or something. Anyway the issue' back :confused:

**Comment by johnny243** [comment]
> Hum, I've encountered another behavior, an infinite page reload :
> 
> ![standard_note_infinite_reload](https://user-images.githubusercontent.com/3978482/74108973-a8043800-4b7f-11ea-9a8c-fa787f433e32.gif)
> 
> But it doesn't always do it ... I'll let you know if a find a regular way of reproducing it.

This shouldn't be happening, as the reload takes place when the tab is **_hidden_**.

Are there any extensions installed in your browser?

**Comment by austil** [comment]
Yup, I have some browser extensions like uBlock Origin, React & Vue dev tools, Grammalecte, ...
I'll disable uBlock for Standard Notes.
Anyway, the bug does not appear anymore (at least for today), I'll stop annoying you :wink: 

Thx for the support.
